"""lpsignal.liquidity's swap checks against the reference TypeScript implementation's vectors (tests/swap_vectors.json,
generated by lpsignal-node scripts/swap-vectors.mjs from a real KyberSwap build and tampered copies of it): every
verdict and every number must match; plus plan_swap with a fake chain and aggregator."""
import json
from pathlib import Path

import pytest
from eth_abi import decode, encode

from lpsignal import liquidity as lp

V = json.loads((Path(__file__).parent / "swap_vectors.json").read_text())


def n(x):
    if isinstance(x, str) and x.startswith("n") and x[1:].lstrip("-").isdigit():
        return int(x[1:])
    if isinstance(x, list):
        return [n(i) for i in x]
    if isinstance(x, dict):
        return {k: n(v) for k, v in x.items()}
    return x


def verdict(call, e):
    try:
        lp.check_swap_call(call, from_token=e["from"]["token"], from_native=e["from"]["native"], to_token=e["to"]["token"], to_native=e["to"]["native"],
                           amount_in=e["amountIn"], account=e["account"], fee_bps=e["feeBps"], min_out=e["minOut"])
        return None
    except lp.SwapRefused as x:
        return str(x)


def test_calldata_verdicts_match_typescript():
    for c in n(V["calls"]):
        assert verdict(c["call"], c["expect"]) == c["verdict"], c["name"]


def test_numbers_match_typescript():
    for sp, in0, a, f, want in n(V["spot"]):
        assert lp.spot_out(sp, in0, a, f) == want
    for s, i, sl, want in n(V["floor"]):
        assert lp.min_out_floor(s, i, sl) == want
    for s, i, sl, need, q, want in n(V["required"]):
        assert lp.required_min_out(s, i, sl, need, q) == want
    for c, fee, impact in V["classes"]:
        assert (lp.swap_fee_bps(c), lp.max_impact_bps(c)) == (fee, impact)
    assert lp.SWAP_FEE_RECEIVER == "0x13ac5bf01871ec16a9a5276f1e167da846af6a33"


# ---- plan_swap against a fake chain and aggregator ----
ME = "0x00000000000000000000000000000000000000aa"
WETH, USDC = "0x4200000000000000000000000000000000000006", "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
POOL = {"chain": "base", "address": "0x6c561b446416e1a00e8e93e221854d6ea4171372", "dex": "uniswap_v3", "token0": WETH, "token1": USDC,
        "decimals0": 18, "decimals1": 6, "fee": 3000, "tickSpacing": 60, "pairClass": "volatile"}
TICK = -200000
SP = lp.sqrt_ratio_at_tick(TICK)


class FakeEth:
    def __init__(self, s):
        self.s, self.chain_id = s, 8453

    def call(self, tx, block_identifier="latest"):
        d = tx["data"]
        if d.startswith("0x" + lp._selector("slot0()").hex()):
            return encode(["uint160", "int24"], [SP, TICK])
        if d.startswith("0x" + lp._selector("allowance(address,address)").hex()):
            return encode(["uint256"], [self.s["allowance"]])
        if tx["to"].lower() == lp.KYBER_ROUTER:
            if self.s["simulate"] == "revert":
                raise ValueError("execution reverted")
            return encode(["uint256", "uint256"], [1, 1])
        raise AssertionError(d[:10])


class FakeW3:
    def __init__(self, s):
        self.eth = FakeEth(s)


@pytest.fixture
def state(monkeypatch):
    s = {"rate": 998, "looser": 0, "allowance": 0, "simulate": "ok", "calls": []}

    def kyber(method, url, body=None):
        s["calls"].append(url)
        if method == "GET":
            from urllib.parse import parse_qs, urlparse
            q = {k: v[0] for k, v in parse_qs(urlparse(url).query).items()}
            assert (q["feeAmount"], q["isInBps"], q["chargeFeeBy"], q["feeReceiver"], q["excludeRFQSources"]) == (q["feeAmount"], "true", "currency_in", lp.SWAP_FEE_RECEIVER, "true")
            a = int(q["amountIn"])
            out = lp.spot_out(SP, q["tokenIn"] != USDC, a, int(q["feeAmount"])) * s["rate"] // 1000
            return {"code": 0, "data": {"routerAddress": "0x6131B5fae19EA4f9D964eAc0408E4408b66337b5", "routeSummary": {
                "tokenIn": q["tokenIn"], "tokenOut": q["tokenOut"], "amountIn": str(a), "amountOut": str(out),
                "extraFee": {"feeAmount": q["feeAmount"], "chargeFeeBy": q["chargeFeeBy"], "isInBps": q["isInBps"] == "true", "feeReceiver": q["feeReceiver"]}}}}
        rs = body["routeSummary"]
        amount, fee, native = int(rs["amountIn"]), int(rs["extraFee"]["feeAmount"]), rs["tokenIn"] == lp.KYBER_NATIVE
        mn = int(rs["amountOut"]) * (10_000 - body["slippageTolerance"] - s["looser"]) // 10_000
        desc = (rs["tokenIn"], rs["tokenOut"], [] if native else ["0xdf033790907c60c9B81aE355F76F74f52F92114A"], [] if native else [amount - amount * fee // 10_000],
                [lp.SWAP_FEE_RECEIVER], [fee], body["recipient"], amount, mn, 0x280, b"")
        data = "0x" + (lp._selector(lp._SWAP_SIG) + encode([f"(address,address,bytes,{lp._SWAP_DESC},bytes)"], [(
            "0x8F10B468b06c6FD214B65F87778827F7D113f996", "0x0000000000000000000000000000000000000000", b"", desc, b"")])).hex()
        return {"code": 0, "data": {"routerAddress": "0x6131B5fae19EA4f9D964eAc0408E4408b66337b5", "data": data, "transactionValue": str(amount if native else 0)}}

    monkeypatch.setattr(lp, "_kyber", kyber)
    return s


def test_plan_swap_native_in(state):
    p = lp.plan_swap(FakeW3(state), POOL, owner=ME, from_side=0, from_native=True, amount_in=10**17)
    assert p["approvals"] == [] and p["simulated"] and p["feeBps"] == 25
    assert (p["swap"]["chainId"], p["swap"]["from"], p["swap"]["to"].lower(), p["swap"]["value"]) == (8453, ME, lp.KYBER_ROUTER, 10**17)
    assert p["minReturn"] >= p["quoteOut"] * 9_949 // 10_000


def test_plan_swap_token_in_needs_an_exact_approval(state):
    p = lp.plan_swap(FakeW3(state), {**POOL, "pairClass": "stable"}, owner=ME, from_side=1, amount_in=1_000_000_000, slippage_bps=10)
    assert len(p["approvals"]) == 1 and p["approvals"][0]["to"].lower() == USDC
    spender, amount = decode(["address", "uint256"], bytes.fromhex(p["approvals"][0]["data"][10:]))
    assert (spender.lower(), amount) == (lp.KYBER_ROUTER, 1_000_000_000)
    assert (p["simulated"], p["feeBps"]) == (False, 5)


def test_plan_swap_refusals(state):
    w3 = FakeW3(state)
    state["rate"] = 900
    with pytest.raises(lp.SwapRefused, match="impact"):
        lp.plan_swap(w3, POOL, owner=ME, from_side=0, from_native=True, amount_in=10**17)
    state["rate"] = 998
    with pytest.raises(lp.SwapRefused, match="moved"):
        lp.plan_swap(w3, POOL, owner=ME, from_side=0, from_native=True, amount_in=10**17, min_out=lp.spot_out(SP, True, 10**17, 25))
    state["looser"] = 20
    with pytest.raises(lp.SwapRefused, match=r"calldata\): minimum"):
        lp.plan_swap(w3, POOL, owner=ME, from_side=0, from_native=True, amount_in=10**17)
    state["looser"], state["simulate"] = 0, "revert"
    with pytest.raises(lp.SwapRefused, match="simulation"):
        lp.plan_swap(w3, POOL, owner=ME, from_side=0, from_native=True, amount_in=10**17)
    with pytest.raises(ValueError, match="v4"):
        lp.plan_swap(w3, {**POOL, "dex": "uniswap_v4"}, owner=ME, from_side=0, amount_in=1)
    with pytest.raises(ValueError, match="wrapped native"):
        lp.plan_swap(w3, POOL, owner=ME, from_side=1, from_native=True, amount_in=1)


def test_plan_swap_refuses_a_slippage_that_would_zero_the_minimum(state):
    w3 = FakeW3(state)
    for bad in (10_000, 20_000, -1, 0.5, True):
        with pytest.raises(ValueError, match="slippage_bps"):
            lp.plan_swap(w3, POOL, owner=ME, from_side=0, from_native=True, amount_in=10**17, slippage_bps=bad)
    with pytest.raises(ValueError, match="min_out"):
        lp.plan_swap(w3, POOL, owner=ME, from_side=0, from_native=True, amount_in=10**17, min_out=-1)
    assert state["calls"] == []  # nothing asked of the aggregator
    assert lp.plan_swap(w3, POOL, owner=ME, from_side=0, from_native=True, amount_in=10**17, slippage_bps=0)["minReturn"] > 0

